DROP TABLE COMMUNITYBOARD;
DROP SEQUENCE SEQ_CB;

CREATE TABLE COMMUNITYBOARD(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(4000) NOT NULL,
	TITLE VARCHAR2(4000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL	
);

CREATE SEQUENCE SEQ_CB NOCACHE;

SELECT * FROM COMMUNITYBOARD;

CREATE TABLE COMMUNITYMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(2000) NOT NULL,
	PW VARCHAR2(2000) NOT NULL,
	NAME VARCHAR2(4000) NOT NULL,
	PHONE VARCHAR2(4000) NOT NULL,
	ENABLED VARCHAR2(500) CHECK(ENABLED IN('Y','N'))
);

CREATE SEQUENCE SEQ_CM NOCACHE;

SELECT * FROM COMMUNITYMEMBER;

INSERT INTO COMMUNITYMEMBER VALUES(SEQ_CM.NEXTVAL, 'ADMIN', 'ADMIN', 'ADMIN', '01011112222', 'Y');